// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oqskfyypcdxscolffawr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xc2tmeXlwY2R4c2NvbGZmYXdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyOTgxOTksImV4cCI6MjA2OTg3NDE5OX0.P3zqdNhHakKqvMGr0x-gebR9_p3K0CgkFp1oOqhV97g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});